[package]
name = "aes-cli"
version = "0.1.0"
authors = ["X5tar <x5tar@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
hex = "0.4.3"
aes = { path = "aes", version = "0.1.0" }
